openapi: 3.0.1
info:
  title: Merchant-Service
  description: Merchant Service API
  contact:
    name: Violet.io
    url: https://violet.io
  version: v1
servers:
- url: https://sandbox-api.violet.io/v1
tags:
- name: Merchants - Address
  description: Operations relating to Merchant Addresses
- name: Merchants - Attribute
  description: Operations relating to Merchant Attributes
- name: Merchants
  description: Merchant related entities
- name: Merchants - Configuration
  description: Operations relating to Merchant Configuration
- name: Merchants - Contributor
  description: Operations relating to Merchant Contributors
- name: Merchants - Credential
  description: Operations relating to Merchant Credentials
- name: Merchants - External
  description: Convenience methods for external merchant management (i.e. createing
    merchants through Violet Connect or ecommerce apps)
- name: Merchants - App Relationships
  description: Merchant App Relationship Endpoints
- name: Merchants - Merchant
  description: Operations directly relating to merchant entities themselves
- name: Merchants - Explore Configuration
  description: Merchant explore configurations
- name: Merchants - Explore
  description: Merchant explore operations
- name: Merchants - Onboarding
  description: Merchant Onboarding Endpoints
- name: Merchants - ReferenceId
  description: Operations relating to Merchant ReferenceIds
- name: Merchants - Setup
  description: Operations relating to Merchant Setups
- name: Merchants - Submission
  description: Operations relating to Merchant Submissions
- name: Merchants - Sync
  description: Sync operations
- name: Merchants - User Merchants
  description: Operations relating to a User's Merchants
- name: Merchants - Util
  description: Various utility operations
paths:
  /merchants/{merchant_id}/configuration:
    get:
      tags:
      - Merchant Configurations
      summary: Get Merchant Configuration
      operationId: getMerchantConfiguration
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantConfiguration'
              example:
                global_feature_flags:
                  sync_metadata: false
                  sync_collections: true
                platform_feature_flags:
                  filter_by_collections: false
                  use_custom_shipping_rates: true
                orders_config:
                  custom_tags:
                  - tag1
                  - tag2
  /merchants/{merchant_id}/configuration/global_feature_flags/{feature_flag}:
    put:
      tags:
      - Merchant Configurations
      summary: Toggle Merchant Config Global Feature Flag
      operationId: updateGlobalFeatureFlag
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: feature_flag
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericToggleSettingRequest'
            example:
              enabled: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantConfiguration'
              example:
                global_feature_flags:
                  sync_metadata: false
                  sync_collections: true
                platform_feature_flags:
                  filter_by_collections: false
                  use_custom_shipping_rates: true
                orders_config:
                  custom_tags:
                  - tag1
                  - tag2
  /merchants/{merchant_id}/configuration/orders_config:
    put:
      tags:
      - Merchant Configurations
      summary: Update Merchants Orders Configuration
      operationId: updateOrdersConfig
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrdersConfig'
            example:
              custom_tags:
              - tag1
              - tag2
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantConfiguration'
              example:
                global_feature_flags:
                  sync_metadata: false
                  sync_collections: true
                platform_feature_flags:
                  filter_by_collections: false
                  use_custom_shipping_rates: true
                orders_config:
                  custom_tags:
                  - tag1
                  - tag2
  /merchants/app_relationships/{app_id}/tax_remitter/{tax_remitter}:
    put:
      operationId: updateTaxRemitterOnMerchantAppRelationships
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: app_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: tax_remitter
        in: path
        required: true
        schema:
          type: string
          enum:
          - APP
          - MERCHANT
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /merchants:
    get:
      tags:
      - Merchants - Merchant
      summary: Get Merchants
      operationId: getAllMerchants
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          format: int32
          default: 20
      - name: exclude_public
        in: query
        description: Exclude public merchants from the result set
        schema:
          type: boolean
          default: false
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VioletPageMerchant'
  /merchants/{merchant_id}:
    get:
      tags:
      - Merchants - Merchant
      summary: Get Merchant
      operationId: getMerchantById
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: merchant_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: app_id
        in: query
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
  /merchants/search:
    post:
      tags:
      - Merchants - Merchant
      summary: Search Merchants
      operationId: searchMerchants
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          format: int32
          default: 20
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantSearchRequest'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VioletPageMerchant'
  /merchants/explore:
    post:
      tags:
      - Merchants - Explore
      summary: Get Merchant Summaries
      operationId: getMerchantSummaries
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          format: int32
          default: 20
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantExploreRequest'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VioletPageMerchantSummary'
components:
  schemas:
    AvailabilityConfig:
      type: object
      properties:
        availabilityRules:
          $ref: '#/components/schemas/AvailabilityRules'
      description: Configurations for the merchants availability behaviors.
    AvailabilityRule:
      type: object
      properties:
        available:
          type: boolean
      description: Configurations for the merchants inventory behaviors.
    AvailabilityRules:
      type: object
      properties:
        tags:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AvailabilityRule'
        categories:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AvailabilityRule'
        collections:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AvailabilityRule'
        vendors:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AvailabilityRule'
    CatalogConfig:
      type: object
      properties:
        inventory:
          $ref: '#/components/schemas/InventoryConfig'
        availability:
          $ref: '#/components/schemas/AvailabilityConfig'
      description: Configurations for the merchants catalog behaviors.
    InventoryConfig:
      type: object
      properties:
        safetyStockRules:
          $ref: '#/components/schemas/StockRules'
      description: Configurations for the merchants inventory behaviors.
    InventoryStockRule:
      type: object
      properties:
        outOfStockLevel:
          type: integer
          format: int32
      description: Configured stock rules that can override the data from the external
        commerce platform.
    MerchantConfiguration:
      type: object
      properties:
        global_feature_flags:
          type: object
          additionalProperties:
            type: boolean
            description: "Feature flags that apply to a merchant globally, regardless\
              \ of their commerce platform."
          description: "Feature flags that apply to a merchant globally, regardless\
            \ of their commerce platform."
        platform_feature_flags:
          type: object
          additionalProperties:
            type: boolean
            description: Feature flags that apply to a merchant depending on their
              commerce platform.
          description: Feature flags that apply to a merchant depending on their commerce
            platform.
        store_config:
          $ref: '#/components/schemas/StoreConfig'
        orders_config:
          $ref: '#/components/schemas/OrdersConfig'
        catalog_config:
          $ref: '#/components/schemas/CatalogConfig'
        shipping_config:
          $ref: '#/components/schemas/ShippingConfig'
      description: A Container for Merchant Configuration info
    OrdersConfig:
      type: object
      properties:
        custom_tags:
          uniqueItems: true
          type: array
          description: Custom tags to be added to a merchants orders upon submission.
          items:
            type: string
            description: Custom tags to be added to a merchants orders upon submission.
        prohibit_order_cancellations:
          type: boolean
          description: Does this merchants prohibit order cancellations.
          default: false
        prohibit_order_refunds:
          type: boolean
          description: Does this merchants prohibit order refunds.
          default: false
      description: Configurations for the merchants order behaviors.
    ShippingConfig:
      type: object
      properties:
        fallback_methods:
          uniqueItems: true
          type: array
          description: Fallback methods to be used when the merchant's system provides
            no shipping methods.
          items:
            $ref: '#/components/schemas/ShippingMethod'
      description: Configurations for the merchants shipping behaviors.
    ShippingMethod:
      type: object
      properties:
        label:
          type: string
        price:
          type: integer
          format: int32
        calculationType:
          type: string
          enum:
          - PER_ORDER
          - PER_ITEM
      description: Fallback methods to be used when the merchant's system provides
        no shipping methods.
    StockRules:
      type: object
      properties:
        tags:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InventoryStockRule'
        categories:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InventoryStockRule'
        collections:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InventoryStockRule'
        vendors:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InventoryStockRule'
      description: Configured stock rules that can override the data from the external
        commerce platform.
    StoreConfig:
      type: object
      properties:
        default_weight_unit:
          type: string
          description: Default weight unit used by the merchant.
          enum:
          - INCHES
          - FEET
          - CENTIMETERS
          - OUNCES
          - POUNDS
          - GRAMS
          - KILOGRAMS
          - CARATS
          - YARDS
          - MILLIMETERS
          - TONNES
          - MILLIGRAMS
          - LITERS
          - MILLILITERS
          - QUARTS
          - QUARTERS
          - GALLONS
          - PINTS
          - METERS
        default_size_unit:
          type: string
          description: Default size unit used by the merchant.
          enum:
          - INCHES
          - FEET
          - CENTIMETERS
          - OUNCES
          - POUNDS
          - GRAMS
          - KILOGRAMS
          - CARATS
          - YARDS
          - MILLIMETERS
          - TONNES
          - MILLIGRAMS
          - LITERS
          - MILLILITERS
          - QUARTS
          - QUARTERS
          - GALLONS
          - PINTS
          - METERS
        default_locale:
          type: string
          description: Default locale used by the merchant.
        default_currency:
          type: string
          description: Default currency code used by the merchant.
          enum:
          - USD
          - AED
          - AFN
          - ALL
          - AMD
          - ANG
          - AOA
          - ARS
          - AUD
          - AWG
          - AZN
          - BAM
          - BBD
          - BDT
          - BGN
          - BIF
          - BMD
          - BND
          - BOB
          - BRL
          - BSD
          - BWP
          - BZD
          - CAD
          - CDF
          - CHF
          - CLP
          - CNY
          - COP
          - CRC
          - CVE
          - CZK
          - DJF
          - DKK
          - DOP
          - DZD
          - EGP
          - ETB
          - EUR
          - FJD
          - FKP
          - GBP
          - GEL
          - GIP
          - GMD
          - GNF
          - GTQ
          - GYD
          - HKD
          - HNL
          - HRK
          - HTG
          - HUF
          - IDR
          - ILS
          - INR
          - ISK
          - JMD
          - JPY
          - KES
          - KGS
          - KHR
          - KMF
          - KRW
          - KYD
          - KZT
          - LAK
          - LBP
          - LKR
          - LRD
          - LSL
          - MAD
          - MDL
          - MGA
          - MKD
          - MMK
          - MNT
          - MOP
          - MRO
          - MUR
          - MVR
          - MWK
          - MXN
          - MYR
          - MZN
          - NAD
          - NGN
          - NIO
          - NOK
          - NPR
          - NZD
          - PAB
          - PEN
          - PGK
          - PHP
          - PKR
          - PLN
          - PYG
          - QAR
          - RON
          - RSD
          - RUB
          - RWF
          - SAR
          - SBD
          - SCR
          - SEK
          - SGD
          - SHP
          - SLL
          - SOS
          - SRD
          - STD
          - SVC
          - SZL
          - THB
          - TJS
          - TOP
          - TRY
          - TTD
          - TWD
          - TZS
          - UAH
          - UGX
          - UYU
          - UZS
          - VND
          - VUV
          - WST
          - XAF
          - XCD
          - XOF
          - XPF
          - YER
          - ZAR
          - ZMW
          - BTN
        base_url:
          type: string
          description: Base URL of the merchant's store.
        base_media_url:
          type: string
          description: Base Media URL of the media from a merchant's store.
      description: Configurations for the merchants store.
    GenericToggleSettingRequest:
      type: object
      properties:
        enabled:
          type: boolean
          description: Is the setting enabled.
      description: Request body for toggling the boolean value of a setting.
    Merchant:
      required:
      - email
      - merchant_name
      - platform
      - user_id
      type: object
      properties:
        id:
          type: integer
          format: int32
        merchant_name:
          type: string
          description: The name of the merchants business
        email:
          type: string
          description: The Merchants unique email address
        user_id:
          type: integer
          description: The Id of the User who owns this Merchant Account
          format: int64
        platform:
          type: string
          description: The eCommerce platform this merchant uses
          enum:
          - OTHER
          - SHOPIFY
          - MAGENTO
          - MAGENTO_ONE
          - WOOCOMMERCE
          - BIGCOMMERCE
          - LIGHTSPEED
          - ECWID
          - YAAS
          - SPREECOMMERCE
          - DEMANDWARE
          - VOLUSION
          - PRESTASHOP
          - THREEDCART
          - SYLIUS
          - WIX
          - SWELL
          - MIVA
          - WEBSPHERE
          - ORACLECC
          - SAPCC
          - SQUARESPACE
          - SHOPWARE
          - COMMERCETOOLS
          - MEDUSA
          - ABICART
          - SPRYKER
          - MYSTORE
          - CENTRA
          - XCART
          - VTEX
          - KIBO
          - SALEOR
          - VENDO
          - CHORD
          - DIGITALRIVER
          - SQUARE
          - AMAZON
          - BIGCARTEL
          - CUSTOM
        platform_plan:
          type: string
          description: The eCommerce platform plan of the store
        store_url:
          type: string
          description: The URL of the Store
        custom_store_url:
          type: string
          description: The custom URL of the Store
        verified:
          type: boolean
          description: If a user has verified their email address. Deprecated (not
            used will always be false)
          deprecated: true
        status:
          type: string
          description: The status of the merchant
          enum:
          - INACTIVE
          - ACTIVE
          - DISABLED
          - NEW
          - DISABLED_INACTIVE
          - FOR_DELETION
          - APPLICATION_IN_PROGRESS
          - APPLICATION_SUBMITTED
          - APPLICATION_DENIED
          - APPLICATION_ACCEPTED
        default_currency:
          type: string
          description: The default currency used by merchant
        default_country_code:
          type: string
          description: The default country of origin of merchant
        default_state_code:
          type: string
          description: The default state / province of origin of merchant
        default_language_code:
          type: string
          description: The default language used by merchant
        commission_rate:
          type: number
          description: The default commission rate of the merchant
          format: double
        date_created:
          type: string
          description: Date of creation
          format: date-time
        date_last_modified:
          type: string
          description: Date of last update
          format: date-time
        external_id:
          type: string
          description: ID of the Merchant on Ecommerce Platform
        distribution_type:
          type: string
          description: Determines if the merchants products are available to all apps
            or only available to apps of their choosing
          enum:
          - PUBLIC
          - PRIVATE
        default_weight_unit:
          type: string
          description: Default Unit of Weight in the Merchants Store
          enum:
          - INCHES
          - FEET
          - CENTIMETERS
          - OUNCES
          - POUNDS
          - GRAMS
          - KILOGRAMS
          - CARATS
          - YARDS
          - MILLIMETERS
          - TONNES
          - MILLIGRAMS
          - LITERS
          - MILLILITERS
          - QUARTS
          - QUARTERS
          - GALLONS
          - PINTS
          - METERS
        default_size_unit:
          type: string
          description: Default Unit of Size in the Merchants Store
          enum:
          - INCHES
          - FEET
          - CENTIMETERS
          - OUNCES
          - POUNDS
          - GRAMS
          - KILOGRAMS
          - CARATS
          - YARDS
          - MILLIMETERS
          - TONNES
          - MILLIGRAMS
          - LITERS
          - MILLILITERS
          - QUARTS
          - QUARTERS
          - GALLONS
          - PINTS
          - METERS
        referral_source:
          type: string
          description: Source of the merchant referral
          enum:
          - VIOLET
          - PLATFORM_MARKETPLACE
          - AFFILIATE_PROGRAM
          - OTHER
        logo:
          type: string
          description: URL of the merchants logo
        category:
          type: string
          description: Merchant Category
          enum:
          - OTHER
          - APPAREL_AND_ACCESSORIES
          - ANIMALS_AND_PET_SUPPLIES
          - ARTS_AND_ENTERTAINMENT
          - BABY_AND_TODDLER
          - BUSINESS_AND_INDUSTRIAL
          - CAMERAS_AND_OPTICS
          - ELECTRONICS
          - FOOD_BEVERAGE_TOBACCO
          - FURNITURE
          - HARDWARE
          - HEALTH_AND_BEAUTY
          - HOME_AND_GARDEN
          - LUGGAGE_AND_BAGS
          - MATURE
          - MEDIA
          - OFFICE_SUPPLIES
          - RELIGIOUS_AND_CEREMONIAL
          - SOFTWARE
          - SPORTING_GOODS
          - TOYS_AND_GAMES
          - VEHICLES_PARTS
        featured:
          type: boolean
          description: Featured Merchant. Deprecated (not used)
          deprecated: true
        connection_status:
          type: string
          description: If a developers application has access to this merchant. Deprecated
            (not reliable) use connection health endpoint instead.
          deprecated: true
          enum:
          - NOT_CONNECTED
          - CONNECTED
          - REQUESTED
          - DECLINED
        shipping_configured:
          type: boolean
          description: The shipping status of the merchant. Deprecated (not reliable)
          deprecated: true
        taxes_configured:
          type: boolean
          description: The tax status of the merchant. Deprecated (not reliable)
          deprecated: true
        default:
          type: boolean
          description: Is this a Users default merchant
        merchantDisabled:
          type: boolean
        billing_configured:
          type: boolean
          description: The billing status of the merchant. Deprecated (not reliable)
            use connection health endpoint instead.
          deprecated: true
      description: Retailer selling goods
    VioletPageMerchant:
      type: object
      properties:
        content:
          type: array
          description: The actual content of the response; A list of the result objects
          items:
            $ref: '#/components/schemas/Merchant'
        last:
          type: boolean
          description: Boolean indicating if this is the last page
        total_pages:
          type: integer
          description: The total count of pages available
          format: int32
        total_elements:
          type: integer
          description: The total count of objects available
          format: int32
        first:
          type: boolean
          description: Boolean indicating if this is the first page of the response
        number_of_elements:
          type: integer
          description: The total number of objects in this specific response
          format: int32
        size:
          type: integer
          description: The page size selected at request time
          format: int32
        number:
          type: integer
          description: The page number selected at request time
          format: int32
        empty:
          type: boolean
          description: Boolean indicating if the response content is empty
        next_page_cursor:
          type: string
          description: Contains the cursor for the next page. This property will only
            be used for situations where the API does not support the page number/page
            size paradigm and it will mutually exclusive with the size/number fields
            in the response. If this property is returned it must be passed when requesting
            the next page from the API. Does not apply to endpoints that do not have
            a next_page_cursor query param documented.
        pageable:
          $ref: '#/components/schemas/VioletPageable'
        sort:
          $ref: '#/components/schemas/VioletSort'
    VioletPageable:
      type: object
      properties:
        page_number:
          type: integer
          description: The current page number (one based)
          format: int32
        page_size:
          type: integer
          description: The number of elements per page
          format: int32
        sort:
          $ref: '#/components/schemas/VioletSort'
        offset:
          type: integer
          description: The offset
          format: int64
        paged:
          type: boolean
          description: Boolean indicating if the result is paged
        unpaged:
          type: boolean
          description: Boolean indicating if the result is unpaged
      description: Violet wrapper for springframework pageable
    VioletSort:
      type: object
      properties:
        unsorted:
          type: boolean
          description: Boolean indicating if the result set is unsorted
        sorted:
          type: boolean
          description: Boolean indicating if the result set is sorted
        empty:
          type: boolean
          description: Boolean indicating if the result set is empty
      description: Violet Wrapper for springframework sort
    MerchantSearchRequest:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the Merchant
          format: int32
        name:
          type: string
          description: The name of the Merchant
        commission_rate_min:
          type: number
          description: The minimum commission rate of the Merchant
          format: double
        commission_rate_max:
          type: number
          description: The maximum commission rate of the Merchant
          format: double
        status:
          type: string
          description: The connection status of the Merchant
          enum:
          - ANY
          - CONNECTED
          - PRIVATE
          - PUBLIC
        sort_by:
          type: string
          description: Property to sort by in camelCase
        sort_direction:
          type: string
          description: Direction to sort by
    MerchantSummary:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          description: The name of the merchants business
        store_url:
          type: string
          description: The URL of the Store
      description: Merchant Summary
    VioletPageMerchantSummary:
      type: object
      properties:
        content:
          type: array
          description: The actual content of the response; A list of the result objects
          items:
            $ref: '#/components/schemas/MerchantSummary'
        last:
          type: boolean
          description: Boolean indicating if this is the last page
        total_pages:
          type: integer
          description: The total count of pages available
          format: int32
        total_elements:
          type: integer
          description: The total count of objects available
          format: int32
        first:
          type: boolean
          description: Boolean indicating if this is the first page of the response
        number_of_elements:
          type: integer
          description: The total number of objects in this specific response
          format: int32
        size:
          type: integer
          description: The page size selected at request time
          format: int32
        number:
          type: integer
          description: The page number selected at request time
          format: int32
        empty:
          type: boolean
          description: Boolean indicating if the response content is empty
        next_page_cursor:
          type: string
          description: Contains the cursor for the next page. This property will only
            be used for situations where the API does not support the page number/page
            size paradigm and it will mutually exclusive with the size/number fields
            in the response. If this property is returned it must be passed when requesting
            the next page from the API. Does not apply to endpoints that do not have
            a next_page_cursor query param documented.
        pageable:
          $ref: '#/components/schemas/VioletPageable'
        sort:
          $ref: '#/components/schemas/VioletSort'
    MerchantExploreRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of Merchant
        sort_by:
          type: string
          description: Property to sort by in camelCase
        sort_direction:
          type: string
          description: Direction to sort by
      description: Merchant Explore Request
